In [16]:
import numpy as np

## Q1

In [2]:
gfg = np.matrix('4 1 9; 12 3 1; 4 5 6')
print("Matrix Sum",gfg.sum())
print("Row Wise sum:\n",gfg.sum(axis=1))
print("Column wis sum:\n",gfg.sum(axis=0))

Matrix Sum 45
Row Wise sum:
 [[14]
 [16]
 [15]]
Column wis sum:
 [[20  9 16]]


## Q2

In [3]:
array=np.array([10, 52, 62, 16, 16, 54, 453])
print("Indices of Sorted array",array.argsort())
array.sort()
print("Sorted array: ",array)
print("Four smallest elements",array[:4 ])
print("Five largest elements",array[-5:])


Indices of Sorted array [0 3 4 1 5 2 6]
Sorted array:  [ 10  16  16  52  54  62 453]
Four smallest elements [10 16 16 52]
Five largest elements [ 16  52  54  62 453]


In [4]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array % 1 == 0]
print("Integer elements only: ",int_elements)
float_elements=array[array % 1 !=0]
print("Float elements only",float_elements)

Integer elements only:  [1. 2. 3. 2.]
Float elements only [1.2 2.2]


## Q2

In [9]:
name="Naman Gupta"
word=name.split()
first_intial=word[0][0]
last_intial=word[-1][0]
sum=ord(first_intial)+ord(last_intial)
dataset=np.linspace(0,200,5,dtype=int)
dataset=dataset+sum
dataset

array([149, 199, 249, 299, 349])

In [10]:
x=dataset[0]
tax_rate=((x % 5) + 5) / 100
taxed_sales=tax_rate*dataset
print("Sales Tax for Each Value:",taxed_sales)

Sales Tax for Each Value: [13.41 17.91 22.41 26.91 31.41]


In [11]:
discounted_sales=np.zeros(5)
for i in range(dataset.size):
    if(dataset[i]<sum+100):
        discounted_sales[i]=dataset[i]-0.05*dataset[i]
    else:
        discounted_sales[i]=dataset[i]-0.1*dataset[i]
discounted_sales

array([141.55, 189.05, 224.1 , 269.1 , 314.1 ])

In [12]:
dataset_weeks=np.broadcast_to(dataset,(3,5))
dataset_weeks=dataset_weeks*1.02
dataset_weeks

array([[151.98, 202.98, 253.98, 304.98, 355.98],
       [151.98, 202.98, 253.98, 304.98, 355.98],
       [151.98, 202.98, 253.98, 304.98, 355.98]])

## Q4

In [13]:
x=np.linspace(-10,10,100)
y=x**2
print(y)

[1.00000000e+02 9.60004081e+01 9.20824406e+01 8.82460973e+01
 8.44913784e+01 8.08182838e+01 7.72268136e+01 7.37169677e+01
 7.02887460e+01 6.69421488e+01 6.36771758e+01 6.04938272e+01
 5.73921028e+01 5.43720029e+01 5.14335272e+01 4.85766758e+01
 4.58014488e+01 4.31078461e+01 4.04958678e+01 3.79655137e+01
 3.55167840e+01 3.31496786e+01 3.08641975e+01 2.86603408e+01
 2.65381084e+01 2.44975003e+01 2.25385165e+01 2.06611570e+01
 1.88654219e+01 1.71513111e+01 1.55188246e+01 1.39679625e+01
 1.24987246e+01 1.11111111e+01 9.80512193e+00 8.58075707e+00
 7.43801653e+00 6.37690032e+00 5.39740843e+00 4.49954086e+00
 3.68329762e+00 2.94867871e+00 2.29568411e+00 1.72431385e+00
 1.23456790e+00 8.26446281e-01 4.99948985e-01 2.55076013e-01
 9.18273646e-02 1.02030405e-02 1.02030405e-02 9.18273646e-02
 2.55076013e-01 4.99948985e-01 8.26446281e-01 1.23456790e+00
 1.72431385e+00 2.29568411e+00 2.94867871e+00 3.68329762e+00
 4.49954086e+00 5.39740843e+00 6.37690032e+00 7.43801653e+00
 8.58075707e+00 9.805121

In [14]:
y=np.sin(x)
print(y)

[ 0.54402111  0.36459873  0.17034683 -0.03083368 -0.23076008 -0.42130064
 -0.59470541 -0.74392141 -0.86287948 -0.94674118 -0.99209556 -0.99709789
 -0.96154471 -0.8868821  -0.77614685 -0.63384295 -0.46575841 -0.27872982
 -0.0803643   0.12126992  0.31797166  0.50174037  0.66510151  0.80141062
  0.90512352  0.97202182  0.99938456  0.98609877  0.93270486  0.84137452
  0.7158225   0.56115544  0.38366419  0.19056796 -0.01027934 -0.21070855
 -0.40256749 -0.57805259 -0.73002623 -0.85230712 -0.93992165 -0.98930624
 -0.99845223 -0.96698762 -0.8961922  -0.78894546 -0.64960951 -0.48385164
 -0.2984138  -0.10083842  0.10083842  0.2984138   0.48385164  0.64960951
  0.78894546  0.8961922   0.96698762  0.99845223  0.98930624  0.93992165
  0.85230712  0.73002623  0.57805259  0.40256749  0.21070855  0.01027934
 -0.19056796 -0.38366419 -0.56115544 -0.7158225  -0.84137452 -0.93270486
 -0.98609877 -0.99938456 -0.97202182 -0.90512352 -0.80141062 -0.66510151
 -0.50174037 -0.31797166 -0.12126992  0.0803643   0

In [15]:
y=np.exp(x)
print(y)

[4.53999298e-05 5.55637361e-05 6.80029415e-05 8.32269459e-05
 1.01859190e-04 1.24662685e-04 1.52571261e-04 1.86727806e-04
 2.28531070e-04 2.79692945e-04 3.42308569e-04 4.18942123e-04
 5.12731841e-04 6.27518520e-04 7.68002806e-04 9.39937692e-04
 1.15036411e-03 1.40789927e-03 1.72308953e-03 2.10884229e-03
 2.58095457e-03 3.15875992e-03 3.86592014e-03 4.73139424e-03
 5.79062440e-03 7.08698731e-03 8.67357053e-03 1.06153465e-02
 1.29918331e-02 1.59003503e-02 1.94600051e-02 2.38165696e-02
 2.91484502e-02 3.56739933e-02 4.36604277e-02 5.34348070e-02
 6.53974032e-02 8.00380986e-02 9.79564464e-02 1.19886224e-01
 1.46725480e-01 1.79573314e-01 2.19774883e-01 2.68976487e-01
 3.29192988e-01 4.02890322e-01 4.93086479e-01 6.03475096e-01
 7.38576715e-01 9.03923902e-01 1.10628782e+00 1.35395549e+00
 1.65706921e+00 2.02804182e+00 2.48206508e+00 3.03773178e+00
 3.71779709e+00 4.55011049e+00 5.56875615e+00 6.81544881e+00
 8.34124196e+00 1.02086186e+01 1.24940499e+01 1.52911270e+01
 1.87143934e+01 2.290403

In [12]:
y=np.log(abs(x)+1)
print(y)

[2.39789527 2.37935906 2.36047276 2.34122289 2.32159517 2.30157448
 2.28114476 2.26028895 2.23898889 2.21722524 2.19497739 2.17222328
 2.14893934 2.12510031 2.10067907 2.07564647 2.04997112 2.02361913
 1.99655388 1.96873568 1.94012142 1.91066421 1.88031287 1.84901141
 1.81669842 1.78330633 1.74876058 1.71297859 1.67586858 1.63732817
 1.59724264 1.55548292 1.51190304 1.46633707 1.41859531 1.36845949
 1.31567679 1.25995207 1.2009379  1.13822143 1.07130684 0.99959153
 0.92233305 0.83860215 0.7472144  0.64662716 0.53477886 0.40882646
 0.26469255 0.09622803 0.09622803 0.26469255 0.40882646 0.53477886
 0.64662716 0.7472144  0.83860215 0.92233305 0.99959153 1.07130684
 1.13822143 1.2009379  1.25995207 1.31567679 1.36845949 1.41859531
 1.46633707 1.51190304 1.55548292 1.59724264 1.63732817 1.67586858
 1.71297859 1.74876058 1.78330633 1.81669842 1.84901141 1.88031287
 1.91066421 1.94012142 1.96873568 1.99655388 2.02361913 2.04997112
 2.07564647 2.10067907 2.12510031 2.14893934 2.17222328 2.1949